# Generated by Django 5.0.3 on 2024-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_uploadedfile_user_csvfile_processingstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="output_file",
            field=models.FileField(blank=True, null=True, upload_to="output_files/"),
        ),
    ]
