# Generated by Django 5.0.3 on 2024-04-13 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_taskresult_user_id_taskresult_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="output_file",
            field=models.FileField(blank=True, null=True, upload_to="output_files/"),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
